import type { Metadata } from "next";
import { Antonio } from "next/font/google";
import "./globals.css";
import "./mdx-styles.css";
import NavBar from "@/components/NavBar";
import { SmoothScrolling } from "@/components/SmoothScroll";

const antonio = Antonio({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${antonio.className} antialiased`}>
        <main className="max-w-full mx-auto">
          <NavBar />
          <SmoothScrolling>
            {children}
          </SmoothScrolling>
        </main>
      </body>
    </html>
  );
}
